#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Guennadi Liakhovetki, DENX Software Engineering, <lg@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= lowlevel_init_spl.o
obj-y	+= board_init_f_spl.o
obj-y	+= ddr2.o
obj-y	+= clock.o
obj-y	+= clock_c.o
obj-y	+= uart.o
obj-y	+= led.o
obj-y	+= nand.o
obj-y	+= tim4.o
obj-y	+= xmodem.o

